In [1]:
pwd

'C:\\Users\\clubc\\Desktop\\python_basic'

In [2]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import BatchNormalization
import numpy
import tensorflow as tf

In [3]:
# seed 값 생성
seed = 0
numpy.random.seed(seed)
tf.random.set_seed(seed)

In [4]:
# 데이터 로드
dataset = numpy.loadtxt("./data_indian/pima-indians-diabetes.csv", delimiter=",")
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [5]:
dataset[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ,   1.   ])

In [6]:
X = dataset[:, 0:8]  # 컬럼 0~7까지를 feature로 한다. list[0:5]
Y = dataset[:, 8]    # 컬럼 8을 class로 한다.

In [7]:
print(X.shape)
X

(768, 8)


array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
print(Y.shape)
Y

(768,)


array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [9]:
# 모델의 설정
model = Sequential()
model.add(Dense(16, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [15]:
# 모델 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
# 모델 실행
model.fit(X, Y, epochs=200, batch_size=10)

Epoch 1/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4622 - accuracy: 0.7799
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4784 - accuracy: 0.7773
Epoch 3/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4915 - accuracy: 0.7669
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5041 - accuracy: 0.7604
Epoch 5/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4619 - accuracy: 0.7839
Epoch 6/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4745 - accuracy: 0.7812
Epoch 7/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4662 - accuracy: 0.7786
Epoch 8/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4720 - accuracy: 0.7708
Epoch 9/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4627 - accuracy: 0.7812
Epoch 10/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4804 - accuracy: 0.7682
Epoch 11/

77/77 [==============================] - 0s 3ms/step - loss: 0.4400 - accuracy: 0.7982
Epoch 84/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4527 - accuracy: 0.7786
Epoch 85/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4498 - accuracy: 0.7839
Epoch 86/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4538 - accuracy: 0.7839
Epoch 87/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4580 - accuracy: 0.7760
Epoch 88/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4391 - accuracy: 0.7956
Epoch 89/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4487 - accuracy: 0.7969
Epoch 90/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4359 - accuracy: 0.8047
Epoch 91/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4568 - accuracy: 0.7852
Epoch 92/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4472 - accuracy: 0.7917
Epoch 93/200


77/77 [==============================] - 0s 3ms/step - loss: 0.4350 - accuracy: 0.7891
Epoch 165/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4280 - accuracy: 0.8112
Epoch 166/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4260 - accuracy: 0.8060
Epoch 167/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4245 - accuracy: 0.8021
Epoch 168/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4338 - accuracy: 0.7878
Epoch 169/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4375 - accuracy: 0.7995
Epoch 170/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4272 - accuracy: 0.8021
Epoch 171/200
77/77 [==============================] - 0s 3ms/step - loss: 0.4138 - accuracy: 0.8047
Epoch 172/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4177 - accuracy: 0.8034
Epoch 173/200
77/77 [==============================] - 0s 4ms/step - loss: 0.4240 - accuracy: 0.8099
Epoc

In [17]:
# 결과 출력
print("\n Accuracy: %.4f" % (model.evaluate(X, Y)[1]))

24/24 [==============================] - 0s 2ms/step - loss: 0.4574 - accuracy: 0.7904

 Accuracy: 0.7904
